version: "2"
services:
  consul:
    image: consul:latest
    ports:
        - 8500:8500
    networks:
        - rabbitmq_go_net
  nestjs:
    build: .
    hostname: "nestjs"
    container_name: "nestjs"
    ports:
        - 3000:3000
        - 3001:3001
    volumes:
        - .env:/usr/src/app/.env
    networks:
        - rabbitmq_go_net
  rabbitmq1:
    build: 
      context: .
      dockerfile: Dockerfile-RMQ
    hostname: "rabbit1"
    container_name: "rabbitmq1"
    ports:
        - 5673:5672
    volumes:
        - rabbitmq1_data:/var/lib/rabbitmq/
        - rabbitmq1_log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        - RABBITMQ_NODENAME=rabbitmq
        - CONSUL_HOST=consul
  rabbitmq2:
    build:
      context: .
      dockerfile: Dockerfile-RMQ
    hostname: "rabbit2"
    container_name: "rabbitmq2"
    ports:
        - 5674:5672
    volumes:
        - rabbitmq2_data:/var/lib/rabbitmq/
        - rabbitmq2_log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        - RABBITMQ_NODENAME=rabbitmq
        - CONSUL_HOST=consul
  rabbitmq3:
    build:
      context: .
      dockerfile: Dockerfile-RMQ
    hostname: "rabbit3"
    container_name: "rabbitmq3"
    ports:
        - 5675:5672
    volumes:
        - rabbitmq3_data:/var/lib/rabbitmq/
        - rabbitmq3_log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        - RABBITMQ_NODENAME=rabbitmq
        - CONSUL_HOST=consul
  haproxy:
    image: haproxy:latest
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
        - rabbitmq_go_net
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  rabbitmq1_data:
    driver: local
  rabbitmq2_data:
    driver: local
  rabbitmq3_data:
    driver: local
  rabbitmq1_log:
    driver: local
  rabbitmq2_log:
    driver: local
  rabbitmq3_log:
    driver: local